metadata:
  display-name: Istio Gateway Helm chart
  short-description: Helm chart for deploying the Istio Gateway.
  featured: false
  home-url: https://istio.io/latest/
  categories:
    - networking
