# syntax=dhi.io/build:2-helm3

name: Prometheus Helm chart 28.x
image: dhi.io/prometheus-chart
variant: helm
tags:
  - 28.16.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_CHART_REFERENCE: dhi/alertmanager-chart:1.42.0@sha256:39073525581d339ad1a0764aca20fa488dea1587458727df8de1d22bc0a45894
  CHART_COMMIT_SHA: 97de013b787ae602d8c24e12f6a82c9bb716927e
  CHART_HELM_NAME: prometheus-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:7.8.1@sha256:d0cfb1794e5da70429b19974b2624e6bbf406dec34e950f15d2c25694fc7fb8a
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.56.3@sha256:61181501bf71c7e56c1a03f9989b6d96e2582df0ac10235187d4d6cde38b62ba
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.93.1-debian13@sha256:8d5d5fd139d10d3c9852c670017981700dbc61820e6b15d18fc5a82af85b1d08
  PROMETHEUS_REFERENCE: dhi/prometheus:3.14.0-debian13@sha256:f18dc10d186c66cf49d6e165f47bd5643dc27f760b20f9ff1d29c690f5da5808
  PUSHGATEWAY_CHART_REFERENCE: dhi/pushgateway-chart:3.8.0@sha256:f6921bd68744803a09bac650a26c9c0e4ec26fd7c5e2297af618c9ca9ff32dcf
  SEMVER_MAJOR_MINOR_VERSION: "28.16"
  SEMVER_MAJOR_VERSION: "28"
  SEMVER_VERSION: 28.16.0
  VERSION: 28.16.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: prometheus-chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-28.16.0
            checksum: 97de013b787ae602d8c24e12f6a82c9bb716927e
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus
          with:
            chart:
              appRef: prometheus
              dependencies:
                - alias: alertmanager
                  condition: alertmanager.enabled
                  name: alertmanager
                  ref: dhi/alertmanager-chart:1.42.0@sha256:39073525581d339ad1a0764aca20fa488dea1587458727df8de1d22bc0a45894
                - alias: kube-state-metrics
                  condition: kube-state-metrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:7.8.1@sha256:d0cfb1794e5da70429b19974b2624e6bbf406dec34e950f15d2c25694fc7fb8a
                - alias: prometheus-node-exporter
                  condition: prometheus-node-exporter.enabled
                  name: prometheus-node-exporter
                  ref: dhi/node-exporter-chart:4.56.3@sha256:61181501bf71c7e56c1a03f9989b6d96e2582df0ac10235187d4d6cde38b62ba
                - alias: prometheus-pushgateway
                  condition: prometheus-pushgateway.enabled
                  name: prometheus-pushgateway
                  ref: dhi/pushgateway-chart:3.8.0@sha256:f6921bd68744803a09bac650a26c9c0e4ec26fd7c5e2297af618c9ca9ff32dcf
              description: Docker Hardened Images Helm chart for Prometheus
              images:
                - name: prometheus
                  ref: dhi/prometheus:3.14.0-debian13@sha256:f18dc10d186c66cf49d6e165f47bd5643dc27f760b20f9ff1d29c690f5da5808
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.93.1-debian13@sha256:8d5d5fd139d10d3c9852c670017981700dbc61820e6b15d18fc5a82af85b1d08
              name: prometheus-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/prometheus/config
