metadata:
  display-name: OpenCost Helm chart
  short-description: OpenCost is a Kubernetes-native cost monitoring and allocation tool.
  featured: false
  home-url: https://github.com/opencost/opencost-helm-chart
  categories:
    - monitoring-and-observability
