# syntax=dhi.io/build:2-helm3

name: Apache Airflow Helm chart 2.x
image: dhi.io/airflow-chart
variant: helm
tags:
  - 2.0.0
platforms:
  - linux/amd64
vars:
  AIRFLOW_REFERENCE: dhi/airflow:3.3.1-python3.13-debian13-compat@sha256:e7848a26e53fd0afcdb5f4e06d1967f08589b20e9e305ad2aef3cce9fd1b4e79
  APPVERSION: 3.3.1
  APPVERSION_MATCH: 3.3.1
  CHART_COMMIT_SHA: 3adbbe1c58e4532df1964cb7794805e763816ee8
  CHART_HELM_NAME: airflow-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GIT_SYNC_REFERENCE: dhi/git-sync:4.7.1-debian13@sha256:ba1647f91dcd8236a87196a0e5ea8f48469bbac625f8907f4024967c241d13ce
  HELM_VERSION: 4.1.4-2
  OPENTELEMETRY_COLLECTOR_REFERENCE: dhi/opentelemetry-collector:0.160.0-debian13-contrib@sha256:16c24ac0dd309e263bdb9fb3ae97c272106ac8c42dc7e943eb610bc186e4295c
  PGBOUNCER_EXPORTER_REFERENCE: dhi/airflow-pgbouncer-exporter:0.20.0-debian13@sha256:003a2737b55c678ba40dd9df59314acf9e8fd875536cd031ec8193e4e0922c92
  PGBOUNCER_REFERENCE: dhi/pgbouncer:1.25.2-debian13@sha256:8cf0957b212bfac27661b557b2f42bce7eaff17aaf30deb8c9311e288beafc9b
  PROMETHEUS_STATSD_EXPORTER_REFERENCE: dhi/prometheus-statsd-exporter:0.31.0-debian13@sha256:df486cc739440de4cc408d5f836c3f37dece8bb7c580f8fc8930eb3cd04be4f2
  REDIS_REFERENCE: dhi/redis:8.10.1-debian13-compat@sha256:cf0b7e048a3b065ce18afc2d55aff086e446f45f7b307105abb0c6a1c8714058
  SEMVER_MAJOR_MINOR_VERSION: "2.0"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.0.0
  VERSION: 2.0.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: airflow
      work-dir: ${source.dir}/helm-charts/chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - yq-go
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/apache/airflow.git#3.3.1
            checksum: 3adbbe1c58e4532df1964cb7794805e763816ee8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: update chart dependencies
          uses: yq/patch@v1
          with:
            file: Chart.yaml
            patches:
              - del(.dependencies[] | select(.name == "postgresql"))
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: airflow
              dependencies: null
              description: Docker Hardened Images Helm chart for Apache Airflow
              images:
                - name: airflow
                  ref: dhi/airflow:3.3.1-python3.13-debian13-compat@sha256:e7848a26e53fd0afcdb5f4e06d1967f08589b20e9e305ad2aef3cce9fd1b4e79
                - name: prometheus-statsd-exporter
                  ref: dhi/prometheus-statsd-exporter:0.31.0-debian13@sha256:df486cc739440de4cc408d5f836c3f37dece8bb7c580f8fc8930eb3cd04be4f2
                - name: pgbouncer
                  ref: dhi/pgbouncer:1.25.2-debian13@sha256:8cf0957b212bfac27661b557b2f42bce7eaff17aaf30deb8c9311e288beafc9b
                - name: airflow-pgbouncer-exporter
                  ref: dhi/airflow-pgbouncer-exporter:0.20.0-debian13@sha256:003a2737b55c678ba40dd9df59314acf9e8fd875536cd031ec8193e4e0922c92
                - name: git-sync
                  ref: dhi/git-sync:4.7.1-debian13@sha256:ba1647f91dcd8236a87196a0e5ea8f48469bbac625f8907f4024967c241d13ce
                - name: redis
                  ref: dhi/redis:8.10.1-debian13-compat@sha256:cf0b7e048a3b065ce18afc2d55aff086e446f45f7b307105abb0c6a1c8714058
                - name: opentelemetry-collector
                  ref: dhi/opentelemetry-collector:0.160.0-debian13-contrib@sha256:16c24ac0dd309e263bdb9fb3ae97c272106ac8c42dc7e943eb610bc186e4295c
              name: airflow-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/apache/airflow
              updateDependencies: true
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: patch pgbouncer command
          runs: |
            set -eux -o pipefail

            yq -i '.pgbouncer.command = ["pgbouncer", "/etc/pgbouncer/pgbouncer.ini"]' values.yaml
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/airflow/config
