# syntax=dhi.io/build:2-debian13

name: Prometheus 3.x
image: dhi.io/prometheus
variant: runtime
tags:
  - "3.14"
  - 3.14.0
  - 3.14-debian
  - 3.14-debian13
  - 3.14.0-debian
  - 3.14.0-debian13
platforms:
  - linux/amd64
  - linux/arm64
vars:
  COMMIT_SHA: d7598b7141418fa35be2b5ec5d0fefb634199610
  DEBIAN_EPOCH_MAJOR_MINOR_VERSION: "3.14"
  DEBIAN_EPOCH_MAJOR_VERSION: "3"
  DEBIAN_EPOCH_VERSION: 3.14.0
  DEBIAN_VERSION: 3.14.0-3
  FLAVORED_SUFFIX: ""
  SUFFIX: ""
  VERSION: 3.14.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  packages:
    - base-files
    - ca-certificates-bundle
    - prometheus-3.14=3.14.0-3
    - tzdata
accounts:
  run-as: nonroot
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
paths:
  - type: directory
    path: /var/prometheus
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /usr/local/bin
    uid: 0
    gid: 0
  - type: symlink
    path: /usr/local/bin/prometheus
    uid: 0
    gid: 0
    source: /usr/bin/prometheus
  - type: symlink
    path: /usr/local/bin/promtool
    uid: 0
    gid: 0
    source: /usr/bin/promtool
annotations:
  org.opencontainers.image.description: A minimal Prometheus image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - prometheus
cmd:
  - --config.file=/etc/prometheus/prometheus.yml
  - --storage.tsdb.path=/var/prometheus
ports:
  - 9090/tcp
