# syntax=dhi.io/build:2-helm3

name: Prometheus NATS Exporter Helm chart 2.x
image: dhi.io/prometheus-nats-exporter-chart
variant: helm
tags:
  - 2.23.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: dfec1b55c688de13b1829738d43087f9842fe795
  CHART_HELM_NAME: prometheus-nats-exporter-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  PROMETHEUS_NATS_EXPORTER_REFERENCE: dhi/prometheus-nats-exporter:0.20.2-debian13@sha256:006eb4059835337a328309b52e33b94ffa6f7f926b65f77dc9d08a6373119813
  SEMVER_MAJOR_MINOR_VERSION: "2.23"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.23.2
  VERSION: 2.23.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: prometheus-nats-exporter-chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-nats-exporter-2.23.2
            checksum: dfec1b55c688de13b1829738d43087f9842fe795
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-nats-exporter
          with:
            chart:
              appRef: prometheus-nats-exporter
              description: Docker Hardened Images Helm chart for Prometheus NATS Exporter
              images:
                - name: prometheus-nats-exporter
                  ref: dhi/prometheus-nats-exporter:0.20.2-debian13@sha256:006eb4059835337a328309b52e33b94ffa6f7f926b65f77dc9d08a6373119813
              name: prometheus-nats-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-nats-exporter
          with:
            cmd: patch
            debug: true
            patches:
              from: ${source.dir}/config
            process-templates: true
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-nats-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-nats-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-nats-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/prometheus-nats-exporter/config
