# No images to configure for this chart.
_internal_defaults_do_not_set:
  securityContext:
    runAsUser: 1337
    runAsGroup: 1337
    fsGroup: 1337
      # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
    sysctls:
    - name: net.ipv4.ip_unprivileged_port_start
      value: "0"

  containerSecurityContext:
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: true
    runAsUser: 1337
    runAsGroup: 1337
    runAsNonRoot: true
