# syntax=dhi.io/build:2-debian13

name: Grafana 13.2.x (dev)
image: dhi.io/grafana
variant: dev
tags:
  - 13-dev
  - 13.2-dev
  - 13.2.1-dev
  - 13-debian-dev
  - 13-debian13-dev
  - 13.2-debian-dev
  - 13.2-debian13-dev
  - 13.2.1-debian-dev
  - 13.2.1-debian13-dev
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2026-08-18"
  end-of-life: "2027-05-18"
vars:
  FLAVORED_SUFFIX: -dev
  GRAFANA_PACKAGE_SUFFIX: ""
  SEMVER_MAJOR_MINOR_VERSION: "13.2"
  SEMVER_MAJOR_VERSION: "13"
  SEMVER_VERSION: 13.2.1
  SUFFIX: -dev
  VERSION: 13.2.1-1
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  packages:
    - '!dpkg'
    - '!gawk'
    - '!libelogind0'
    - '!libslang2'
    - '!original-awk'
    - '!tar'
    - apt
    - base-files
    - bash
    - ca-certificates-bundle
    - coreutils
    - diffutils
    - dpkg
    - findutils
    - grafana-13.2=13.2.1-1
    - grep
    - libc-bin
    - libc6
    - libgcc-s1
    - libstdc++6
    - mawk
    - perl-base
    - sed
    - tar
    - tzdata
    - util-linux
accounts:
  root: true
  run-as: root
  users:
    - name: grafana
      uid: 65532
      gid: 65532
    - name: _apt
      uid: 42
      gid: 65532
  groups:
    - name: grafana
      gid: 65532
      members:
        - grafana
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
work-dir: /var/lib/grafana
environment:
  DEBIAN_FRONTEND: noninteractive
  GRAFANA_VERSION: 13.2.1
  PATH: /usr/share/grafana/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin
paths:
  - type: directory
    path: /etc/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/alerting
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/dashboards
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/datasources
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/provisioning/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /etc/grafana/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/lib/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/lib/grafana/plugins
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /var/log/grafana
    uid: 65532
    gid: 65532
    mode: "0755"
  - type: directory
    path: /tmp
    uid: 65532
    gid: 65532
    mode: "0777"
annotations:
  org.opencontainers.image.description: A minimal Grafana image
  org.opencontainers.image.licenses: AGPL-3.0
entrypoint:
  - grafana
  - server
  - --homepath=/usr/share/grafana
  - --config=/etc/grafana/grafana.ini
  - --packaging=docker
  - cfg:default.log.mode=console
  - cfg:default.paths.data=/var/lib/grafana
  - cfg:default.paths.logs=/var/log/grafana
  - cfg:default.paths.plugins=/var/lib/grafana/plugins
  - cfg:default.paths.provisioning=/etc/grafana/provisioning
ports:
  - 3000/tcp
