defaults:
  statefulSetRecreateJob:
    image:
      registry: ${kubectl.registry}
      repository: ${kubectl.repository}
      tag: ${kubectl.tag}@${kubectl.digest}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532

loki:
  image:
    registry: ${loki.registry}
    repository: ${loki.repository}
    tag: ${loki.tag}
    digest: ${loki.digest}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532

memcached:
  image:
    registry: ${memcached.registry}
    repository: ${memcached.repository}
    tag: ${memcached.tag}@${memcached.digest}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 11211
    runAsGroup: 11211
    fsGroup: 11211

memcachedExporter:
  image:
    registry: ${memcached-exporter.registry}
    repository: ${memcached-exporter.repository}
    tag: ${memcached-exporter.tag}@${memcached-exporter.digest}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532

test:
  image:
    registry: ${loki-helm-test.registry}
    repository: ${loki-helm-test.repository}
    tag: ${loki-helm-test.tag}
    digest: ${loki-helm-test.digest}

lokiCanary:
  image:
    registry: ${loki-canary.registry}
    repository: ${loki-canary.repository}
    tag: ${loki-canary.tag}
    digest: ${loki-canary.digest}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532

gateway:
  image:
    registry: ${nginx.registry}
    repository: ${nginx.repository}
    tag: ${nginx.tag}@${nginx.digest}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532
  metrics:
    image:
      registry: ${access-log-exporter.registry}
      repository: ${access-log-exporter.repository}
      tag: ${access-log-exporter.tag}@${access-log-exporter.digest}

sidecar:
  image:
    registry: ${k8s-sidecar.registry}
    repository: ${k8s-sidecar.repository}
    tag: ${k8s-sidecar.tag}@${k8s-sidecar.digest}
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532

adminApi:
  podSecurityContext:
    runAsNonRoot: true
    runAsGroup: 65532
    runAsUser: 65532

rollout_operator:
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532
