# syntax=dhi.io/build:2-helm3

name: Envoy Gateway Helm chart 1.8.x
image: dhi.io/envoy-gateway-chart
variant: helm
tags:
  - 1.8.4
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 85e602c3f3fc2598875687f3d477b73716aeb817
  CHART_HELM_NAME: envoy-gateway-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  ENVOY_GATEWAY_REFERENCE: dhi/envoy-gateway:1.8.4-debian13@sha256:b4a5d9a366ebb98e3b5b938328fbebd1e8c30496c3f959071d37e0e9212834ab
  ENVOY_RATELIMIT_REFERENCE: dhi/envoy-ratelimit:1631871c92e531b5a0c19f1e5661887c0d9bd8f0-debian13@sha256:f0f58a0ea131c19caa1cdd4a4ea568dce36e7755ecc211e48e2031e5bb6a7c81
  ENVOY_REFERENCE: dhi/envoy:1.39.1-debian13@sha256:f60014e8b4ec4f5d3041cc571e777f15fda346e6797d00139166f0cccb166307
  HELM_VERSION: 4.1.4-2
  SEMVER_MAJOR_MINOR_VERSION: "1.8"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.8.4
  VERSION: 1.8.4
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: envoy-gateway-chart
      work-dir: ${source.dir}/helm-charts/charts/gateway-helm
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - yq-go
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/envoyproxy/gateway.git#v1.8.4
            checksum: 85e602c3f3fc2598875687f3d477b73716aeb817
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: envoy-gateway
              description: Docker Hardened Images Helm chart for Envoy Gateway
              images:
                - name: envoy-gateway
                  ref: dhi/envoy-gateway:1.8.4-debian13@sha256:b4a5d9a366ebb98e3b5b938328fbebd1e8c30496c3f959071d37e0e9212834ab
                - name: envoy-ratelimit
                  ref: dhi/envoy-ratelimit:1631871c92e531b5a0c19f1e5661887c0d9bd8f0-debian13@sha256:f0f58a0ea131c19caa1cdd4a4ea568dce36e7755ecc211e48e2031e5bb6a7c81
                - name: envoy
                  ref: dhi/envoy:1.39.1-debian13@sha256:f60014e8b4ec4f5d3041cc571e777f15fda346e6797d00139166f0cccb166307
              name: envoy-gateway-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/envoyproxy/gateway
            cmd: prepare
            registry: dhi.io
        - name: update version
          uses: yq/patch@v1
          with:
            file: Chart.yaml
            patches:
              - .version = "1.8.4"
        - name: rename values file
          runs: |
            set -eux -o pipefail

            mv values.tmpl.yaml values.yaml
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: verify templated variables
          runs: |
            set -eux -o pipefail

            if grep -E '\$\{[^}]+\}' values.yaml; then
              exit 1
            fi
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/envoy-gateway/config
