# syntax=dhi.io/build:2-helm3

name: External Secrets Operator Helm chart 2.x
image: dhi.io/external-secrets-chart
variant: helm
tags:
  - 2.10.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 8488600898e856d74a7e0f53ed5e3cc79d89f4e8
  CHART_HELM_NAME: external-secrets-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  EXTERNAL_SECRETS_REFERENCE: dhi/external-secrets:2.10.0-debian13@sha256:a0312e93d4afae83e50a2ef4b6cbd458457b763eda63448669440cb000952b6d
  HELM_VERSION: 4.1.4-2
  SEMVER_MAJOR_MINOR_VERSION: "2.10"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.10.0
  VERSION: 2.10.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: external-secrets
      work-dir: ${source.dir}/helm-charts/deploy/charts/external-secrets
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - gawk
          - sed
          - yq-go
          - make
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/external-secrets/external-secrets.git#helm-chart-2.10.0
            checksum: 8488600898e856d74a7e0f53ed5e3cc79d89f4e8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: external-secrets
              description: Docker Hardened Images Helm chart for External Secrets Operator
              images:
                - name: external-secrets
                  ref: dhi/external-secrets:2.10.0-debian13@sha256:a0312e93d4afae83e50a2ef4b6cbd458457b763eda63448669440cb000952b6d
              name: external-secrets-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/external-secrets/external-secrets
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: blank 3rd party images
          runs: |
            set -eux -o pipefail

            yq eval 'del(.dependencies)' Chart.yaml \
              | awk '{print} END{print ""}' > tmp && mv tmp Chart.yaml
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: dependency update
        - name: generate CRDs
          runs: |
            set -eux -o pipefail

            cd ${source.dir}/helm-charts

            make helm.generate
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/external-secrets/config
