#!/bin/sh
set -e

case "$1" in
    configure)
        setcap cap_net_admin,cap_net_raw+ep /usr/lib/klipper-lb/xtables-nft-multi
        setcap cap_net_admin,cap_net_raw+ep /usr/lib/klipper-lb/xtables-legacy-multi
        ;;
esac
