metadata:
  display-name: MLflow Helm chart
  short-description: MLflow is an open source platform for managing the end-to-end machine learning lifecycle, including experiment tracking, model registry, and deployment.
  featured: false
  home-url: https://github.com/mlflow/mlflow/tree/master/charts
  categories:
    - machine-learning-and-ai
