# syntax=dhi.io/build:2-helm3

name: Istio ZTunnel Helm chart 1.x
image: dhi.io/ztunnel-chart
variant: helm
tags:
  - 1.28.10
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: ff49c1889ebad8d444b8f82425a2fd326c039e54
  CHART_HELM_NAME: ztunnel-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  SEMVER_MAJOR_MINOR_VERSION: "1.28"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.28.10
  VERSION: 1.28.10
  ZTUNNEL_REFERENCE: dhi/ztunnel:1.28.10-debian13@sha256:ec684dce7ec5257bb02782935fb8032436ce0fe983cae556c0a844e947221694
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: ztunnel
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/istio/istio.git#1.28.10
            checksum: ff49c1889ebad8d444b8f82425a2fd326c039e54
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts/ztunnel
          with:
            chart:
              appRef: ztunnel
              description: Docker Hardened Images Helm chart for ZTunnel
              images:
                - name: ztunnel
                  ref: dhi/ztunnel:1.28.10-debian13@sha256:ec684dce7ec5257bb02782935fb8032436ce0fe983cae556c0a844e947221694
              name: ztunnel-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts/ztunnel
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/manifests/charts/ztunnel
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts
          with:
            chart: ztunnel
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/manifests/charts/ztunnel
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/ztunnel/config
