metadata:
  display-name: Kyverno Reports Server Helm chart
  short-description: Kyverno reports server provides a scalable solution for storing policy reports and cluster policy reports.
  featured: false
  home-url: https://github.com/kyverno/reports-server/tree/main/charts/reports-server
  categories:
    - security
