# syntax=dhi.io/build:2-helm3

name: Grafana Loki Helm chart 18.x
image: dhi.io/loki-chart
variant: helm
tags:
  - 18.12.1
platforms:
  - linux/amd64
vars:
  ACCESS_LOG_EXPORTER_REFERENCE: dhi/access-log-exporter:0.4.13-debian13@sha256:f6b27fb92bb859c5e240d5eb16e5590043770202370c19afa5ca31b79331008c
  APPVERSION: 3.7.7
  CHART_COMMIT_SHA: a4f70397da3e281bdfb610f7183dc6c44ca1c168
  CHART_HELM_NAME: loki-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_ROLLOUT_OPERATOR_CHART_REFERENCE: dhi/grafana-rollout-operator-chart:0.51.1@sha256:8f57695edf160db7bbd1e85802e885dd504d59e928de640dcbefee814fcb76c5
  HELM_VERSION: 4.1.4-2
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.11.2-debian13@sha256:8caae30eab172418208fc636e0c286fecddaea82e7fda766ad5e0cedaa9d1f10
  KUBECTL_REFERENCE: dhi/kubectl:1.36.4-debian13@sha256:f5d1e38dc82870673e06710665ee18147f89678613482a00a337a7dc572bdd48
  LOKI_CANARY_REFERENCE: dhi/loki-canary:3.7.7-debian13@sha256:b792a9c615a66f4be3278718491350e8bb7e5cfb08a33f59a88aa5de5c7b1237
  LOKI_HELM_TEST_REFERENCE: dhi/loki-helm-test:3.7.7-debian13@sha256:19e32cff4e755aebbdd1a6aa5b9bc4ed10415fb2a16b5e780b2478ca0f9fde8c
  LOKI_REFERENCE: dhi/loki:3.7.7-debian13@sha256:21baeb7f86e042f9202dc307c4fe8b13189d8fc4820187295b4cdb8a816d7339
  MEMCACHED_EXPORTER_REFERENCE: dhi/memcached-exporter:0.17.0-debian13@sha256:aaeb600d85a0c55673f05a239b63500b4b7708276ed2e2148a51e465fba113a4
  MEMCACHED_REFERENCE: dhi/memcached:1.6.45-debian13@sha256:aee0937cd22b97b370c611fcd0066fb4803b33e29910be18a50272440aa21d18
  NGINX_REFERENCE: dhi/nginx:1.31.5-debian13@sha256:a7437d28bd9e71884845c7f6e560463de7b061e6efc889df237bc937b1eb18cd
  SEMVER_MAJOR_MINOR_VERSION: "18.12"
  SEMVER_MAJOR_VERSION: "18"
  SEMVER_VERSION: 18.12.1
  VERSION: 18.12.1
  checksum: 02327afab1a59e6a4abc504fac25467772b32b1f
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: loki
      work-dir: ${source.dir}/helm-charts/charts/loki
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#loki-18.12.1
            checksum: a4f70397da3e281bdfb610f7183dc6c44ca1c168
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: loki
              debug: true
              dependencies:
                - alias: rollout_operator
                  condition: rollout_operator.enabled
                  name: rollout-operator
                  ref: dhi/grafana-rollout-operator-chart:0.51.1@sha256:8f57695edf160db7bbd1e85802e885dd504d59e928de640dcbefee814fcb76c5
              description: Docker Hardened Images Helm chart for Grafana Loki
              images:
                - name: loki
                  ref: dhi/loki:3.7.7-debian13@sha256:21baeb7f86e042f9202dc307c4fe8b13189d8fc4820187295b4cdb8a816d7339
                - name: loki-canary
                  ref: dhi/loki-canary:3.7.7-debian13@sha256:b792a9c615a66f4be3278718491350e8bb7e5cfb08a33f59a88aa5de5c7b1237
                - name: loki-helm-test
                  ref: dhi/loki-helm-test:3.7.7-debian13@sha256:19e32cff4e755aebbdd1a6aa5b9bc4ed10415fb2a16b5e780b2478ca0f9fde8c
                - name: nginx
                  ref: dhi/nginx:1.31.5-debian13@sha256:a7437d28bd9e71884845c7f6e560463de7b061e6efc889df237bc937b1eb18cd
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.11.2-debian13@sha256:8caae30eab172418208fc636e0c286fecddaea82e7fda766ad5e0cedaa9d1f10
                - name: memcached
                  ref: dhi/memcached:1.6.45-debian13@sha256:aee0937cd22b97b370c611fcd0066fb4803b33e29910be18a50272440aa21d18
                - name: memcached-exporter
                  ref: dhi/memcached-exporter:0.17.0-debian13@sha256:aaeb600d85a0c55673f05a239b63500b4b7708276ed2e2148a51e465fba113a4
                - name: access-log-exporter
                  ref: dhi/access-log-exporter:0.4.13-debian13@sha256:f6b27fb92bb859c5e240d5eb16e5590043770202370c19afa5ca31b79331008c
                - name: kubectl
                  ref: dhi/kubectl:1.36.4-debian13@sha256:f5d1e38dc82870673e06710665ee18147f89678613482a00a337a7dc572bdd48
              name: loki-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/loki
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . --set loki.useTestSchema=true
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/loki/config
