# syntax=dhi.io/build:2-helm3

name: OpenTelemetry Operator Helm chart 0.x
image: dhi.io/opentelemetry-operator-chart
variant: helm
tags:
  - 0.122.0
platforms:
  - linux/amd64
vars:
  APPVERSION: 0.158.0
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:eb0e5b0b63bf4f8570e9d7d1787fc6c3be218dae07035de8fe41497778aa3338
  CHART_COMMIT_SHA: b9a6b0597a2a79131a8a065c4e7accc3b232c99a
  CHART_HELM_NAME: opentelemetry-operator-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  OPENTELEMETRY_AUTOINSTRUMENTATION_GO_REFERENCE: dhi/opentelemetry-autoinstrumentation-go:0.24.0-debian13@sha256:042d017e62447590a48535375468bff1a516e5eaec379f55a92c0ca5ffe61857
  OPENTELEMETRY_COLLECTOR_REFERENCE: dhi/opentelemetry-collector:0.158.0-debian13@sha256:e4e03f1cb0a5315a952bccbe714954306a00ac2334d23004b8c1da251daaa1c8
  OPENTELEMETRY_OPERATOR_REFERENCE: dhi/opentelemetry-operator:0.158.0-debian13@sha256:61ff95ee9d7104f156f7fede7e40f47b99650369faef96826d3e0c6cea99c020
  SEMVER_MAJOR_MINOR_VERSION: "0.122"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.122.0
  VERSION: 0.122.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: opentelemetry-operator
      work-dir: ${source.dir}/helm-charts/charts/opentelemetry-operator
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/open-telemetry/opentelemetry-helm-charts.git#opentelemetry-operator-0.122.0
            checksum: b9a6b0597a2a79131a8a065c4e7accc3b232c99a
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: opentelemetry-operator
              description: Docker Hardened Images Helm chart for OpenTelemetry Operator
              images:
                - name: opentelemetry-operator
                  ref: dhi/opentelemetry-operator:0.158.0-debian13@sha256:61ff95ee9d7104f156f7fede7e40f47b99650369faef96826d3e0c6cea99c020
                - name: opentelemetry-collector
                  ref: dhi/opentelemetry-collector:0.158.0-debian13@sha256:e4e03f1cb0a5315a952bccbe714954306a00ac2334d23004b8c1da251daaa1c8
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:eb0e5b0b63bf4f8570e9d7d1787fc6c3be218dae07035de8fe41497778aa3338
                - name: opentelemetry-autoinstrumentation-go
                  ref: dhi/opentelemetry-autoinstrumentation-go:0.24.0-debian13@sha256:042d017e62447590a48535375468bff1a516e5eaec379f55a92c0ca5ffe61857
              name: opentelemetry-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/open-telemetry/opentelemetry-helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opentelemetry-operator/config
