# syntax=dhi.io/build:2-helm3

name: Kube State Metrics Helm chart 6.x
image: dhi.io/kube-state-metrics-chart
variant: helm
tags:
  - 6.4.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 439ccfe5ace5cfaa947af4145332a6beebf09a1c
  CHART_HELM_NAME: kube-state-metrics-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.20.2-debian13@sha256:b760dd671f97747bfbc65f16ee610017b3ef1157e026969d3d893fe65c55dc74
  KUBE_STATE_METRICS_REFERENCE: dhi/kube-state-metrics:2.17.0-debian13@sha256:0265699bb30c9c0a566220eaddf7c181b6a200c89e82fb74537c4549c8b9917f
  SEMVER_MAJOR_MINOR_VERSION: "6.4"
  SEMVER_MAJOR_VERSION: "6"
  SEMVER_VERSION: 6.4.2
  VERSION: 6.4.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kube-state-metrics-chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-state-metrics-6.4.2
            checksum: 439ccfe5ace5cfaa947af4145332a6beebf09a1c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            chart:
              appRef: kube-state-metrics
              description: Docker Hardened Images Helm chart for Kube State Metrics
              images:
                - name: kube-state-metrics
                  ref: dhi/kube-state-metrics:2.17.0-debian13@sha256:0265699bb30c9c0a566220eaddf7c181b6a200c89e82fb74537c4549c8b9917f
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.20.2-debian13@sha256:b760dd671f97747bfbc65f16ee610017b3ef1157e026969d3d893fe65c55dc74
              name: kube-state-metrics-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-state-metrics
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-state-metrics/config
