# syntax=dhi.io/build:2-helm3

name: Kube Prometheus Stack Helm chart 82.x
image: dhi.io/kube-prometheus-stack-chart
variant: helm
tags:
  - 82.18.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.31.1-debian13@sha256:c879b6be51b415b07a39a041f4fd15dbba6a3848297c49617a7483b88df9021a
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:eb0e5b0b63bf4f8570e9d7d1787fc6c3be218dae07035de8fe41497778aa3338
  CHART_COMMIT_SHA: 3eafe12613fffe3deb5a7f4c2251bec83bc064ed
  CHART_HELM_NAME: kube-prometheus-stack-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:11.6.1@sha256:3bdfa1b5eac6859435f75fee3526bb378942d772a026fcb40bc41cd521b8466b
  HELM_VERSION: 4.1.4-2
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:7.2.2@sha256:350b93e7950f105926104bdd12ff446a325bb2bc06704c07bf50320f20644893
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.8-debian13@sha256:6aed899264ea93b2d78d387e35aab65390cb70f70712d153a70b78f90f58ab5c
  KUBECTL_REFERENCE: dhi/kubectl:1.36.4-debian13@sha256:f5d1e38dc82870673e06710665ee18147f89678613482a00a337a7dc572bdd48
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.53.1@sha256:b2affdb982fd469419ef8f5b48203d416bc53691ee09844f9ac0096b3edeb98d
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:a3081c112bdd2a293294112cbe7ddb12a20c02ec2fd911b81b6d2f4332335d62
  PROMETHEUS_OPERATOR_ADMISSION_WEBHOOK_REFERENCE: dhi/prometheus-operator-admission-webhook:0.89.0-debian13@sha256:eabcf22d4c192f70d89889dc8549212fcd467afdd6bf8577a6fd4aa6b2b1d5b3
  PROMETHEUS_OPERATOR_REFERENCE: dhi/prometheus-operator:0.89.0-debian13@sha256:f8fbbedaebaf049f2c7943df40286e8ff5e27e355610c9fe99dc17baca23da86
  PROMETHEUS_REFERENCE: dhi/prometheus:3.11.3-debian13@sha256:e7e82ee5d73f7b5eaabc0e23e0160059dcfe01bfbd78609e4ca865a10cfa995a
  SEMVER_MAJOR_MINOR_VERSION: "82.18"
  SEMVER_MAJOR_VERSION: "82"
  SEMVER_VERSION: 82.18.0
  THANOS_REFERENCE: dhi/thanos:0.41.0-debian13@sha256:37a6e48edfeab2eb1e2db2e018d0f596008df0e56e5fe4483544b3a617df5ac5
  VERSION: 82.18.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kube-prometheus-stack-chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - yq-go
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-prometheus-stack-82.18.0
            checksum: 3eafe12613fffe3deb5a7f4c2251bec83bc064ed
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            chart:
              appRef: prometheus-operator
              dependencies:
                - condition: crds.enabled
                  keep: true
                  name: crds
                - alias: kube-state-metrics
                  condition: kubeStateMetrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:7.2.2@sha256:350b93e7950f105926104bdd12ff446a325bb2bc06704c07bf50320f20644893
                - alias: prometheus-node-exporter
                  condition: nodeExporter.enabled
                  name: node-exporter
                  ref: dhi/node-exporter-chart:4.53.1@sha256:b2affdb982fd469419ef8f5b48203d416bc53691ee09844f9ac0096b3edeb98d
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:11.6.1@sha256:3bdfa1b5eac6859435f75fee3526bb378942d772a026fcb40bc41cd521b8466b
              description: Docker Hardened Images Helm chart for Kube Prometheus Stack
              images:
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:eb0e5b0b63bf4f8570e9d7d1787fc6c3be218dae07035de8fe41497778aa3338
                - name: kubectl
                  ref: dhi/kubectl:1.36.4-debian13@sha256:f5d1e38dc82870673e06710665ee18147f89678613482a00a337a7dc572bdd48
                - name: alertmanager
                  ref: dhi/alertmanager:0.31.1-debian13@sha256:c879b6be51b415b07a39a041f4fd15dbba6a3848297c49617a7483b88df9021a
                - name: prometheus-operator-admission-webhook
                  ref: dhi/prometheus-operator-admission-webhook:0.89.0-debian13@sha256:eabcf22d4c192f70d89889dc8549212fcd467afdd6bf8577a6fd4aa6b2b1d5b3
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.8-debian13@sha256:6aed899264ea93b2d78d387e35aab65390cb70f70712d153a70b78f90f58ab5c
                - name: prometheus-operator
                  ref: dhi/prometheus-operator:0.89.0-debian13@sha256:f8fbbedaebaf049f2c7943df40286e8ff5e27e355610c9fe99dc17baca23da86
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:a3081c112bdd2a293294112cbe7ddb12a20c02ec2fd911b81b6d2f4332335d62
                - name: thanos
                  ref: dhi/thanos:0.41.0-debian13@sha256:37a6e48edfeab2eb1e2db2e018d0f596008df0e56e5fe4483544b3a617df5ac5
                - name: prometheus
                  ref: dhi/prometheus:3.11.3-debian13@sha256:e7e82ee5d73f7b5eaabc0e23e0160059dcfe01bfbd78609e4ca865a10cfa995a
              name: kube-prometheus-stack-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            file: values.yaml
            patches:
              - del(.prometheus-windows-exporter)
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kube-prometheus-stack
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-prometheus-stack/config
