_internal_defaults_do_not_set:
  global:
    proxy:
      image: ${proxyv2.registry}/${proxyv2.repository}:${proxyv2.tag}@${proxyv2.digest}

  gateways:
    istio-egressgateway:
      runAsRoot: false
