# syntax=dhi.io/build:2-alpine3.23

image: dhi.io/pkg-helm
variant: runtime
tags:
  - 3.21.4-alpine3.23
  - 3.21.4-r5-alpine3.23
platforms:
  - linux/amd64
  - linux/arm64
vars:
  COMMIT_SHA: 813176c51bb5c181dbbd7901298ddcc104cd3417
  GOLANG_VERSION: 1.26.8-r0
  PACKAGE_NAME: helm-3
  REL: "5"
  SEMVER_MAJOR_MINOR_VERSION: "3.21"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.21.4
  VERSION: 3.21.4
contents:
  repositories:
    - https://dhi.io/apk/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
  keyring:
    - https://dhi.io/keyring/dhi-apk@docker-0F81AD7700D99184.rsa.pub
  packages:
    - alpine-baselayout-data
  builds:
    - name: helm-3
      work-dir: /go/src/github.com/helm/helm
      contents:
        packages:
          - busybox
          - bash
          - ca-certificates-bundle
          - golang-1.26=1.26.8-r0
          - golang-1.26-oci-config=1.26.8-r0
          - sed
        files:
          - url: git+https://github.com/helm/helm.git#v3.21.4
            checksum: 813176c51bb5c181dbbd7901298ddcc104cd3417
            path: /go/src/github.com/helm/helm
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies (3 only)
          uses: go/bump@v1
          with:
            deps:
              - golang.org/x/crypto@v0.56.0
              - oras.land/oras-go/v2@v2.6.2
            tidy: true
        - uses: go/hermetic@v1
        - name: build
          uses: go/build@v1
          environment:
            GOFLAGS: -buildvcs=false
          with:
            cgo_enabled: 0
            fips: false
            ldflags:
              - -X helm.sh/helm/v3/internal/version.version=3.21.4
              - -X helm.sh/helm/v3/internal/version.gitCommit=813176c51bb5c181dbbd7901298ddcc104cd3417
              - -X helm.sh/helm/v3/internal/version.gitTreeState=clean
              - -X helm.sh/helm/v3/internal/version.metadata=
            output: ${target.dir}/usr/bin/helm
            packages: ./cmd/helm
        - name: build dev
          uses: go/build@v1
          environment:
            GOFLAGS: -buildvcs=false
          with:
            cgo_enabled: 0
            fips: false
            ldflags:
              - -X helm.sh/helm/v3/internal/version.version=3.21.4
              - -X helm.sh/helm/v3/internal/version.gitCommit=813176c51bb5c181dbbd7901298ddcc104cd3417
              - -X helm.sh/helm/v3/internal/version.gitTreeState=clean
              - -X helm.sh/helm/v3/internal/version.metadata=
            output: ${target.dir}/usr/bin/helm-dev
            packages: ./cmd/helm
            strip: false
        - uses: dhi/build-pkg:0
          with:
            description: The Kubernetes Package Manager
            files:
              - usr/bin/helm
            license: Apache-2.0
            name: helm-3
            provides: helm=3.21.4-r5
            rel: 5
            replaces: helm
            subpackages:
              - files:
                  - path: usr/bin/helm
                    source: usr/bin/helm-dev
                name: helm-3-dev
            url: https://github.com/helm/helm
            version: 3.21.4
os-release:
  name: Docker Hardened Images (Alpine)
  id: alpine
  version-id: "3.23"
  pretty-name: Docker Hardened Images/Alpine Linux v3.23
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
