# syntax=dhi.io/build:2-alpine3.24

image: dhi.io/pkg-nginx-prometheus-exporter
variant: runtime
tags:
  - 1.5.3-alpine3.24
  - 1.5.3-r5-alpine3.24
platforms:
  - linux/amd64
  - linux/arm64
vars:
  COMMIT_SHA: 9956da7073198e272ff915c5e06c360290c50b6b
  GOLANG_MAJOR_MINOR_VERSION: "1.26"
  GOLANG_VERSION: 1.26.8-r0
  REL: "5"
  SEMVER_MAJOR_MINOR_VERSION: "1.5"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.5.3
  VERSION: 1.5.3
contents:
  repositories:
    - https://dhi.io/apk/alpine/v3.24/main
    - https://dhi.io/apk/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
  keyring:
    - https://dhi.io/keyring/dhi-apk@docker-0F81AD7700D99184.rsa.pub
  packages:
    - alpine-baselayout-data
  builds:
    - name: nginx-prometheus-exporter
      work-dir: /go/src/github.com/nginx/nginx-prometheus-exporter
      contents:
        packages:
          - busybox
          - bash
          - ca-certificates-bundle
          - coreutils
          - findutils
          - mawk
          - sed
          - golang-1.26=1.26.8-r0
          - golang-1.26-oci-config=1.26.8-r0
        files:
          - url: git+https://github.com/nginx/nginx-prometheus-exporter.git#v1.5.3
            checksum: 9956da7073198e272ff915c5e06c360290c50b6b
            path: /go/src/github.com/nginx/nginx-prometheus-exporter
            spdx:
              name: nginx-exporter
              version: 1.5.3
              packages:
                - name: nginx-exporter
                  purl: pkg:golang/nginx/nginx-prometheus-exporter@1.5.3
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          work-dir: /go/src/github.com/nginx/nginx-prometheus-exporter
          with:
            deps:
              - golang.org/x/crypto@v0.56.0
        - name: test
          work-dir: /go/src/github.com/nginx/nginx-prometheus-exporter
          privileged: true
          runs: |
            set -eux -o pipefail

            CGO_ENABLED=0 go test .
        - name: build
          uses: go/build@v1
          work-dir: /go/src/github.com/nginx/nginx-prometheus-exporter
          with:
            fips: false
            ldflags:
              - -X github.com/prometheus/common/version.Version=1.5.3
              - -X github.com/prometheus/common/version.Revision=9956da7073198e272ff915c5e06c360290c50b6b
              - -X github.com/prometheus/common/version.Branch=1.5.3
              - -X github.com/prometheus/common/version.BuildUser=dhi
              - -X github.com/prometheus/common/version.BuildDate=$(date -u -d @${SOURCE_DATE_EPOCH} +'%Y-%m-%dT%H:%M:%SZ')
            output: ${target.dir}/usr/bin/nginx-prometheus-exporter
            packages: .
        - name: build dev
          uses: go/build@v1
          work-dir: /go/src/github.com/nginx/nginx-prometheus-exporter
          with:
            fips: false
            ldflags:
              - -X github.com/prometheus/common/version.Version=1.5.3
              - -X github.com/prometheus/common/version.Revision=9956da7073198e272ff915c5e06c360290c50b6b
              - -X github.com/prometheus/common/version.Branch=1.5.3
              - -X github.com/prometheus/common/version.BuildUser=dhi
              - -X github.com/prometheus/common/version.BuildDate=$(date -u -d @${SOURCE_DATE_EPOCH} +'%Y-%m-%dT%H:%M:%SZ')
            output: ${target.dir}/usr/bin/nginx-prometheus-exporter-dev
            packages: .
            strip: false
        - uses: dhi/build-pkg:0
          with:
            description: Nginx-prometheus-exporter
            files:
              - usr/bin/nginx-prometheus-exporter
            license: Apache-2.0
            name: nginx-prometheus-exporter
            rel: 5
            subpackages:
              - files:
                  - path: usr/bin/nginx-prometheus-exporter
                    source: usr/bin/nginx-prometheus-exporter-dev
                name: nginx-prometheus-exporter-dev
            url: https://github.com/nginx/nginx-prometheus-exporter
            version: 1.5.3
os-release:
  name: Docker Hardened Images (Alpine)
  id: alpine
  version-id: "3.24"
  pretty-name: Docker Hardened Images/Alpine Linux v3.24
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
