metadata:
  display-name: Istio CNI Helm chart
  short-description: Helm chart for deploying the Istio CNI plugin.
  featured: false
  home-url: https://istio.io/latest/
  categories:
    - networking
