#!/bin/sh
set -e

# Re-apply Linux file capabilities on FRR daemons at package configure time.
# dpkg preserves xattrs when they are set before packaging, but FRR's
# capabilities are applied after make install and are more reliably enforced
# via postinst (same setcap values as image/frr).
case "${1:-configure}" in
configure)
	setcap 'cap_net_bind_service,cap_net_raw=+p' /usr/lib/frr/babeld
	setcap 'cap_net_bind_service,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/bfdd
	setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/bgpd
	setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw=+p' /usr/lib/frr/eigrpd
	setcap 'cap_net_bind_service,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/fabricd
	setcap 'cap_net_bind_service,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/isisd
	setcap 'cap_net_admin,cap_net_bind_service=+p' /usr/lib/frr/ldpd
	setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/mgmtd
	setcap 'cap_net_admin,cap_net_raw,cap_dac_override=+p' /usr/lib/frr/nhrpd
	setcap 'cap_net_bind_service,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/ospf6d
	setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/ospfd
	setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw=+p' /usr/lib/frr/pbrd
	setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/pim6d
	setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/pimd
	setcap 'cap_net_bind_service,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/ripd
	setcap 'cap_net_bind_service,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/ripngd
	setcap 'cap_net_raw=+p' /usr/lib/frr/vrrpd
	setcap 'cap_net_admin,cap_net_raw,cap_sys_admin=+p' /usr/lib/frr/zebra
	;;
esac

exit 0
