# syntax=dhi.io/build:2-helm3

name: Homepage Helm chart 1.x
image: dhi.io/homepage-chart
variant: helm
tags:
  - 1.0.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 5f03b6d3af8857512f14eca10a586e44fb35b275
  CHART_HELM_NAME: homepage-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  HOMEPAGE_REFERENCE: dhi/homepage:1.13.2-debian13@sha256:1a44e529a537cde0b057d29270ff1ce4d265b8000770a5074d21133a1c5400d8
  SEMVER_MAJOR_MINOR_VERSION: "1.0"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.0.0
  VERSION: 1.0.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: homepage
      work-dir: ${source.dir}/helm-charts/homepage
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/docker-hardened-images/helm-charts.git#homepage/1.0.0
            checksum: 5f03b6d3af8857512f14eca10a586e44fb35b275
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: homepage
              description: Docker Hardened Images Helm chart for Homepage
              images:
                - name: homepage
                  ref: dhi/homepage:1.13.2-debian13@sha256:1a44e529a537cde0b057d29270ff1ce4d265b8000770a5074d21133a1c5400d8
              name: homepage-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/docker-hardened-images/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/homepage/config
