metadata:
  display-name: Kyverno Policies Helm chart
  short-description: Kubernetes Pod Security Standards implemented as Kyverno policies.
  featured: false
  home-url: https://github.com/kyverno/kyverno/tree/main/charts/kyverno-policies
  categories:
    - security
