plugins:
  install:
    fullImageName: ${curl.registry}/${curl.repository}:${curl.tag}@${curl.digest}
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65532

opencost:
  exporter:
    image:
      registry: ${opencost.registry}
      repository: ${opencost.repository}
      tag: ${opencost.tag}@${opencost.digest}
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001

  ui:
    image:
      registry: ${opencost-ui.registry}
      repository: ${opencost-ui.repository}
      tag: ${opencost-ui.tag}@${opencost-ui.digest}
    securityContext:
      capabilities:
        drop:
        - ALL
      # readOnlyRootFilesystem: true # Cannot be true because user 65532 writes to /etc/nginx in entrypoint
      runAsNonRoot: true
      runAsUser: 65532

  sigV4Proxy:
    image: ${aws-sigv4-proxy.registry}/${aws-sigv4-proxy.repository}:${aws-sigv4-proxy.tag}@${aws-sigv4-proxy.digest}
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65532

podSecurityContext:
  fsGroup: 1001
