#!/bin/bash
# SPDX-License-Identifier: MIT
# Derived from go-gitea/gitea docker/rootless/usr/local/bin/environment-to-ini.
# Adapted for DHI: the binary is installed by the gitea Hardened System
# Package at /usr/bin/gitea instead of /app/gitea/gitea.
exec /usr/bin/gitea config edit-ini --in-place --apply-env "$@"
