# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.20.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.20.3
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.20.3-debian13@sha256:452e7f63910d939408cce9b35e0bfcf6c58a8a4836faec6feab3d7b5bf5bd196
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.20.3-debian13@sha256:2cf8428b979f2a2c4bc6f2a043550488b66ab0c05bc69b7d81c7a4ba53b37800
  CERT_MANAGER_COMMIT_SHA: 1e1d16d1744e6d9c80e464e58e8d9ab1caed222b
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.20.3-debian13@sha256:881e223f80d1ed05defbd19d8a78bee6a6c4c323645792b2f35f92510e7be874
  CERT_MANAGER_MAJOR_MINOR_VERSION: "1.20"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.20.3-debian13@sha256:d59d5d994326f9dce46c950ddab2bf32a252dba51ba1ee0ec1424060d733d1a2
  CERT_MANAGER_VERSION: 1.20.3
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.20.3-debian13@sha256:f593184c542954eaabcaf20c4f891d24e673ad4781b81352875ff5e0dc058c4f
  CHART_HELM_NAME: cert-manager-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: cert-manager
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - make
          - curl
          - git
          - grep
          - gawk
          - findutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.20.3
            checksum: 1e1d16d1744e6d9c80e464e58e8d9ab1caed222b
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.20.3-debian13@sha256:881e223f80d1ed05defbd19d8a78bee6a6c4c323645792b2f35f92510e7be874
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.20.3-debian13@sha256:2cf8428b979f2a2c4bc6f2a043550488b66ab0c05bc69b7d81c7a4ba53b37800
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.20.3-debian13@sha256:452e7f63910d939408cce9b35e0bfcf6c58a8a4836faec6feab3d7b5bf5bd196
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.20.3-debian13@sha256:d59d5d994326f9dce46c950ddab2bf32a252dba51ba1ee0ec1424060d733d1a2
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.20.3-debian13@sha256:f593184c542954eaabcaf20c4f891d24e673ad4781b81352875ff5e0dc058c4f
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
