# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.21.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.21.1
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.21.1-debian13@sha256:65da8fa398a378b07137905b7262fab50f182fb3bc2796a3a8b4c2523fec3f82
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.21.1-debian13@sha256:4cfc3e10339df65fe218a05d598fa30d3e2503f92f49eb5e7e65f8ee9440f6f3
  CERT_MANAGER_COMMIT_SHA: 24e33194fb39488eff2bbf10c6dc640f407cad44
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.21.1-debian13@sha256:169e6a9a6b175937f77877d1619821e5c37c2116625b71ebfb788c9630911f9a
  CERT_MANAGER_MAJOR_MINOR_VERSION: "1.21"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.21.1-debian13@sha256:180f4fbdc5ac620e236d8ef5220b29a8d69cc015f9f55ad624026af1e35a06f1
  CERT_MANAGER_VERSION: 1.21.1
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.21.1-debian13@sha256:14466e59a763ef550c5b8cbfbb74b0c6c122fc0b29123d6c93b297147312ecd1
  CHART_HELM_NAME: cert-manager-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: cert-manager
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - make
          - curl
          - git
          - grep
          - gawk
          - findutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.21.1
            checksum: 24e33194fb39488eff2bbf10c6dc640f407cad44
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              chartVersion: 1.21.1
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.21.1-debian13@sha256:169e6a9a6b175937f77877d1619821e5c37c2116625b71ebfb788c9630911f9a
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.21.1-debian13@sha256:4cfc3e10339df65fe218a05d598fa30d3e2503f92f49eb5e7e65f8ee9440f6f3
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.21.1-debian13@sha256:65da8fa398a378b07137905b7262fab50f182fb3bc2796a3a8b4c2523fec3f82
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.21.1-debian13@sha256:180f4fbdc5ac620e236d8ef5220b29a8d69cc015f9f55ad624026af1e35a06f1
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.21.1-debian13@sha256:14466e59a763ef550c5b8cbfbb74b0c6c122fc0b29123d6c93b297147312ecd1
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
