# syntax=dhi.io/build:2-helm3

name: Vault Helm chart 0.x
image: dhi.io/vault-chart
variant: helm
tags:
  - 0.34.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: aa1c92e4adddbce9660e536dfe5222a88eda6d52
  CHART_HELM_NAME: vault-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  SEMVER_MAJOR_MINOR_VERSION: "0.34"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.34.1
  VAULT_CSI_PROVIDER_REFERENCE: dhi/vault-csi-provider:1.7.4-debian13@sha256:be3deaff1a39c4984e09d2a7dd1f1eb4bcb84c54dec1297d71464e0dc400b4e1
  VAULT_HELM_REFERENCE: dhi/vault:1.21.4-debian13-helm@sha256:d06c18f734dacbb695fee1c7d9d0be7d66ea2497b0a5b036ad1fc47252a6e834
  VAULT_K8S_REFERENCE: dhi/vault-k8s:1.7.6-debian13@sha256:2aff078d1ece51c22204c1cc973f63a4721eacd8e93c093eba6c3523f80ca01a
  VAULT_REFERENCE: dhi/vault:1.21.4-debian13@sha256:76681c3b07dcd1cc7b49c151b842b55ae57d2ea209fd653631005c14dc5c7a81
  VERSION: 0.34.1
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: vault
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/hashicorp/vault-helm.git#v0.34.1
            checksum: aa1c92e4adddbce9660e536dfe5222a88eda6d52
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart:
              appRef: vault
              description: Docker Hardened Images Helm chart for Vault
              images:
                - name: vault
                  ref: dhi/vault:1.21.4-debian13@sha256:76681c3b07dcd1cc7b49c151b842b55ae57d2ea209fd653631005c14dc5c7a81
                - name: vault-helm
                  ref: dhi/vault:1.21.4-debian13-helm@sha256:d06c18f734dacbb695fee1c7d9d0be7d66ea2497b0a5b036ad1fc47252a6e834
                - name: vault-k8s
                  ref: dhi/vault-k8s:1.7.6-debian13@sha256:2aff078d1ece51c22204c1cc973f63a4721eacd8e93c093eba6c3523f80ca01a
                - name: vault-csi-provider
                  ref: dhi/vault-csi-provider:1.7.4-debian13@sha256:be3deaff1a39c4984e09d2a7dd1f1eb4bcb84c54dec1297d71464e0dc400b4e1
              name: vault-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/hashicorp/vault-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vault/config
