# syntax=dhi.io/build:2-helm3

name: External DNS Helm chart 1.x
image: dhi.io/external-dns-chart
variant: helm
tags:
  - 1.21.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 9f26451346774099a8b3e3e5cc46a53bf2fd1461
  CHART_HELM_NAME: external-dns-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  EXTERNAL_DNS_REFERENCE: dhi/external-dns:0.21.0-debian13@sha256:f093b6bedc6e24c1ff1ea2df1882440b8391470ff05e68544acbd1c32a369464
  HELM_VERSION: 4.1.4-2
  SEMVER_MAJOR_MINOR_VERSION: "1.21"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.21.1
  VERSION: 1.21.1
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: external-dns
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/kubernetes-sigs/external-dns.git#external-dns-helm-chart-1.21.1
            checksum: 9f26451346774099a8b3e3e5cc46a53bf2fd1461
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/external-dns
          with:
            chart:
              appRef: external-dns
              description: Docker Hardened Images Helm chart for External DNS
              images:
                - name: external-dns
                  ref: dhi/external-dns:0.21.0-debian13@sha256:f093b6bedc6e24c1ff1ea2df1882440b8391470ff05e68544acbd1c32a369464
              name: external-dns-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kubernetes-sigs/external-dns
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/external-dns
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/external-dns
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: external-dns
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/external-dns
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/external-dns/config
