# syntax=dhi.io/build:2-debian13

image: dhi.io/pkg-docker-compose-plugin
variant: runtime
tags:
  - 5.5.1
  - 5.5.1-r0
  - 5.5.1-debian13
  - 5.5.1-r0-debian13
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2026-07-07"
vars:
  COMMIT_SHA: 5f94fb0aa42a2cd1248c6e6c7fafb87546b9c8de
  GOLANG_MAJOR_MINOR_VERSION: "1.26"
  GOLANG_VERSION: 1.26.8-0
  REL: "0"
  SEMVER_MAJOR_MINOR_VERSION: "5.5"
  SEMVER_MAJOR_VERSION: "5"
  SEMVER_VERSION: 5.5.1
  VERSION: 5.5.1
contents:
  packages:
    - base-files
  builds:
    - name: docker-compose-plugin deb
      work-dir: /go/src/github.com/docker/compose
      caches:
        - path: /go/pkg/mod
      contents:
        repositories:
          - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
        keyring:
          - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
        packages:
          - bash
          - ca-certificates-bundle
          - coreutils
          - findutils
          - golang-1.26=1.26.8-0
          - golang-1.26-oci-config=1.26.8-0
        files:
          - url: git+https://github.com/docker/compose.git#v5.5.1
            checksum: 5f94fb0aa42a2cd1248c6e6c7fafb87546b9c8de
            path: /go/src/github.com/docker/compose
            spdx:
              name: docker-compose
              version: 5.5.1
              packages:
                - name: docker-compose
                  purl: pkg:golang/github.com/docker/compose/v5@5.5.1
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: update compose go dependencies
          uses: go/bump@v2
          with:
            deps:
              - golang.org/x/mod@v0.40.0
              - golang.org/x/text@v0.41.0
              - golang.org/x/crypto@v0.56.0
            download: true
        - name: test compose after dependency updates
          runs: |
            set -eux -o pipefail

            go test -count=1 -timeout=5m -tags e2e ./cmd
        - name: build compose
          uses: go/build@v1
          with:
            ldflags:
              - -X github.com/docker/compose/v5/internal.Version=v5.5.1
            output: ${target.dir}/usr/libexec/docker/cli-plugins/docker-compose
            packages: ./cmd
            tags: e2e
        - uses: dhi/build-pkg:0
          with:
            description: Docker Compose (V2) plugin for the Docker CLI
            files:
              - usr/libexec/docker/cli-plugins/docker-compose
            formats:
              - deb
            license: Apache-2.0
            name: docker-compose-plugin
            rel: 0
            url: https://github.com/docker/compose
            version: 5.5.1
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
