metadata:
  display-name: Harbor Helm chart
  short-description: Harbor - An open source trusted cloud native registry that stores, signs, and scans content
  featured: false
  home-url: https://goharbor.io/
  categories:
    - developer-tools
    - security
