# Docker Hardened Images configuration for OpenTelemetry Operator

manager:
  image:
    repository: ${opentelemetry-operator.registry}/${opentelemetry-operator.repository}
    tag: ${opentelemetry-operator.tag}@${opentelemetry-operator.digest}
  collectorImage:
    repository: ${opentelemetry-collector.registry}/${opentelemetry-collector.repository}
    tag: ${opentelemetry-collector.tag}@${opentelemetry-collector.digest}
  autoInstrumentationImage:
    # To enable Go instrumentation, manager.autoInstrumentation.go.enabled must be set to true
    go:
      repository: ${opentelemetry-autoinstrumentation-go.registry}/${opentelemetry-autoinstrumentation-go.repository}
      tag: ${opentelemetry-autoinstrumentation-go.tag}@${opentelemetry-autoinstrumentation-go.digest}


testFramework:
  image:
    repository: ${busybox.registry}/${busybox.repository}
    tag: ${busybox.tag}@${busybox.digest}
